Bench 216: Checkout Page
answerdigital/AnswerKing-React pull request #27
Opened 2022-11-24 14:22 UTC by harrystead2

![burgerdemo2](https://user-images.githubusercontent.com/88429620/203806750-34db3852-dc45-45b4-af08-c7dc8a9c3f0c.gif)

2022-11-24 15:46 UTC, JavedK15 commented on src/components/Navigation/Navigation.tsx
> +        </NavLink>
Do we want this in the nav bar? I feel like it should live on the order summary on the right of the screen?

2022-11-24 15:47 UTC, JavedK15 commented
There's a few build warnings we can get rid of

2022-11-24 15:49 UTC, JavedK15 commented on src/components/Navigation/Navigation.tsx
> +        </NavLink>
I see that it already does. I just don't think we need it on the nav bar as well

2022-11-25 09:32 UTC, mbaltrimas approved these changes, later dismissed

2022-11-25 09:44 UTC, JavedK15 commented
Are we still getting build warnings? We should be looking to remove those to keep the code clean. It seems to be mainly for unused variables. Make sure to check the build log before pushing for PR, will speed things up a bit 👍

2022-11-25 09:49 UTC, JavedK15 approved these changes, later dismissed

2022-11-25 09:57 UTC, mbaltrimas requested changes

2022-11-25 09:57 UTC, mbaltrimas commented on src/components/OrderCreateForm/OrderCreateForm.tsx
> +import { FormEvent, ReactElement, useState } from 'react';
one more warning

2022-11-25 10:00 UTC, mbaltrimas approved these changes

2022-11-25 10:00 UTC, JavedK15 approved these changes

2022-11-25 10:05 UTC, merged