BENCH-242 Menu Page update
answerdigital/AnswerKing-React pull request #87
Opened 2023-01-20 16:20 UTC by AudriusPutys

![menu_page](https://user-images.githubusercontent.com/116072957/213749979-e26cfc5e-3163-4529-bbac-9d28fb533760.gif)

2023-01-23 09:08 UTC, harrystead2 requested changes

2023-01-23 09:08 UTC, harrystead2 commented on src/components/LocalOrderDetails/LocalOrderDetails.tsx
> +                <div className="text-poppins col-span-1 flex items-center justify-center rounded bg-gray-200 text-sm">{lineItem.quantity}</div>
font-poppins, not text-poppins

2023-01-23 09:08 UTC, harrystead2 commented on src/components/MenuItems/MenuItems.tsx
> +      <div className="mb-12 mr-10 grid max-h-[60vh] grid-cols-3 overflow-auto px-16">
Try to use precise measurements e.g mb-[20px], don't have to always if its like mb-1 or mt-2, but it is easier to read for larger measurements.

2023-01-23 09:08 UTC, harrystead2 commented on src/components/OrderType/OrderType.tsx
> +            className={`font-poppins rounded-xl ${activeButton == 1 ? 'bg-[#ffffff]' : ''} px-4 text-[#333F4C] hover:cursor-pointer hover:bg-gray-50`}
If you rebase, font-poppins should be applied everywhere now so no need to use it again and again in classes. Would only need to change font weight and style individually.

2023-01-23 09:08 UTC, harrystead2 commented on src/pages/Menu/Menu.tsx
> +        <div className="col-span-3 mt-32">
Would probably make this a percentage - e.g mb-[something%], or add the panel component alongside the cards.

2023-01-23 09:12 UTC, harrystead2 commented
### Styling Changes: 

### General
1. Black or dark colour is #333F4C, not fully black. 
2. Padding and margin not quite right in most places. 
3. Fonts wrong in most places, including Menu title. 

### Tabs
1. When you click on Sides tab, burgers appear. But nothing appears in burgers
   tab at the start - why? Is that a problem with the filter on frontend or did you add
   products called burger to sides on backend?
2. change font-thin to font-[300] on text in tabs.
3. change text size on tabs to be 16px.
4. each tab should have a width of 72px and height of 32px,  
5. distance between tabs should be 40px. 

### Cards
1. Padding is wrong - between picture and title, between title and description, between 
description and button, between button and bottom of card.
2. Cards look too wide and not long enough - should be 247.33px wide and 365px high.
3. Pictures looks stretched out? Probably because of 2. But if still stretched out 
   there's other things to use to get it looking better.
4. No 'new' or 'recommended' tag in top left of one of the cards. Not sure if this will 
   come from backend in future, but would be nice to manually add it to one of the 
   cards for now. 
5. There shouldn't be a scroll bar between cards and panel. Should only be a scroll
   bar on far right at end of screen. 
6. Font is wrong on description. Shouldn't be bold. Might need to get the italicised
   poly font from google. Should be font-[400], that's if we have the poly 400 italicised
   version, if not need to pull from google fonts. 
7. Font is wrong on buttons. Should not be fully bold. Should be - font-[400].
8. The 'Served on a brioche bun' subheading should be fully white, not greyed out. 

### Panel
1. No need for delivery/collection tab on panel. 
2. Use Bin component I made for trash icon (rebase to develop to get it).
3. Shouldn't be a line underneath last item in panel - use this - [&:not(:last-child)]:border-b
4. Icon sizes for quantity and trash not quite right - should be 30px high and 30px wide. 
5. Should be no scroll bar on bar - should grow as items are added. Remove overflow and add 'grow'.
6. Service charge ps are too big and should not be bold. 
7. No need for delivery fee - remove. 
8. Padding not right between service charge and total. 
9. Total font size too big - should be 20px. 
10. Margin between back to start screen and allergen board button not quite right, and should also
     be slightly bigger than panel on both sides. 
11. Font not right either on buttons below panel, should be - text-14px, font-poppins, font-[400], leading-[21px], text- 
      [#A2AAB6] 
12. Panel itself is not correct size, should be width: 357px; height: 618px;
13. Panel should be closer to middle. 
14. Top of panel should be in line with the divider between items and category names. 
15. Padding between quantity/trash icon and name/price is wrong.

2023-01-23 09:13 UTC, harrystead2 commented
I'll look into the code smell, might have to make the arrow function a normal function for now.

2023-01-23 10:43 UTC, harrystead2 commented
> I'll look into the code smell, might have to make the arrow function a normal function for now.

Yeah for performance, address the smell and change to a normal function

2023-01-24 14:39 UTC, harrystead2 commented on src/components/OrderCreateForm/OrderCreateForm.tsx
> +  const noProductsInBasket = localOrder.lineItems?.length === 0;
rename this to - lineItemsExist

2023-01-24 15:30 UTC, harrystead2 approved these changes, later dismissed

2023-01-24 15:32 UTC, bethcryer requested changes

2023-01-24 15:32 UTC, bethcryer commented on src/pages/Menu/Menu.tsx
> +          <div className="font-poly mb-6 text-lg italic text-[#E4EAEB]">Served on a brioche bun with house fries and fresh salad</div>
Should this be using the selected category's `description` field?

2023-01-24 15:34 UTC, harrystead2 commented on src/pages/Menu/Menu.tsx
> +          <div className="font-poly mb-6 text-lg italic text-[#E4EAEB]">Served on a brioche bun with house fries and fresh salad</div>
Ooo yes

2023-01-24 15:56 UTC, AudriusPutys commented on src/pages/Menu/Menu.tsx
> +          <div className="font-poly mb-6 text-lg italic text-[#E4EAEB]">Served on a brioche bun with house fries and fresh salad</div>
good catch, updated now

2023-01-24 15:57 UTC, harrystead2 approved these changes

2023-01-24 16:03 UTC, bethcryer approved these changes

2023-01-24 16:04 UTC, merged