Bench 327: Menu Product Modal
answerdigital/AnswerKing-React pull request #98
Opened 2023-01-27 16:30 UTC by NogaAD

![Modal2](https://user-images.githubusercontent.com/115239141/216086249-39624ac7-4c6a-4c41-8e44-ee58d7d16ad4.gif)

2023-01-30 10:51 UTC, harrystead2 requested changes

2023-01-30 10:51 UTC, harrystead2 commented on src/components/Icons/CheckBoxIcon.tsx
> +          <svg className="duration-300" width="37" height="37" viewBox="0 0 37 37" fill="none" xmlns="http://www.w3.org/2000/svg">
These SVGs should be imported and used within img tags - import img from '../assets/..'  <img src={img}>

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +    } else {
Is the else necessary?

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  // const ingredients = ['Patty', 'Bun', 'Lettuce', 'Ketchup', 'Hummus', 'Tahini'];
remove comments

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <h5 className="font-poppins text-xl font-semibold text-[#333F4C]">{product.name}</h5>
shouldn't need to add font-poppins anywhere, it should be default

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <h5 className="font-poppins text-xl font-semibold text-[#333F4C]">{product.name}</h5>
use exact font weight i.e font-[400] as stated in figma

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +          {/* Ingredients and AddOns
remove comments - don't think ingredients and addOns will be implemented in API for a while so best to just get rid for now

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +          onClick={(e) => e.stopPropagation()}
is this necessary? what's it for?

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/Modal.tsx
> +
I don't think this component is necessary, just wrap the productModal in the conditional and delete this

2023-01-30 10:51 UTC, harrystead2 commented on src/context/orderReducer.tsx
> +      if (lineItemQuantity === 0) {
Might be wrong because just had a glance. But is this necessary? Does this not return the same as the last return statement?

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  };
add spacing between functions

2023-01-30 10:51 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +    } else {
I thinking removing it would solve the bug too

2023-01-30 10:51 UTC, harrystead2 commented on src/context/OrderContext.tsx
> +    <LocalOrderContext.Provider value={{ localOrder, addToLocalOrder, removeProduct, setOrderId, removeLocalOrder }}>
one of the code smells wants this to be wrapped in a memo, which makes sense - function Component() {
  const foo = useMemo(() => ({foo: 'bar'}), []);
  return (
    <SomeContext.Provider value={foo}>
      <SomeComponent />
    </SomeContext.Provider>
  );
}

2023-01-30 13:31 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <h5 className="font-poppins text-xl font-semibold text-[#333F4C]">{product.name}</h5>
semibold is font-[600] which is what is stated in figma.

2023-01-30 13:34 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +          onClick={(e) => e.stopPropagation()}
To prevent disabling the modal when clicking the modal itself.

2023-01-30 14:53 UTC, NogaAD commented on src/components/Icons/CheckBoxIcon.tsx
> +          <svg className="duration-300" width="37" height="37" viewBox="0 0 37 37" fill="none" xmlns="http://www.w3.org/2000/svg">
Done

2023-01-30 14:53 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +    } else {
Done

2023-01-30 14:54 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  // const ingredients = ['Patty', 'Bun', 'Lettuce', 'Ketchup', 'Hummus', 'Tahini'];
Done

2023-01-30 14:54 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <h5 className="font-poppins text-xl font-semibold text-[#333F4C]">{product.name}</h5>
Removed

2023-01-30 14:54 UTC, NogaAD commented on src/components/MenuProductModal/Modal.tsx
> +
Done

2023-01-30 14:54 UTC, NogaAD commented on src/context/orderReducer.tsx
> +      if (lineItemQuantity === 0) {
Removed

2023-01-30 14:55 UTC, NogaAD commented on src/context/OrderContext.tsx
> +    <LocalOrderContext.Provider value={{ localOrder, addToLocalOrder, removeProduct, setOrderId, removeLocalOrder }}>
Done

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +    <>
remove fragments

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +        <>
remove fragments

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +            className="fixed inset-0 z-50 flex items-center justify-center overflow-x-auto overflow-y-auto
remove overflows, we don't want scroll bars on the modal.

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +            className="fixed inset-0 z-50 flex items-center justify-center overflow-x-auto overflow-y-auto
I don't think we should be setting the z-index nor the inset. It should be something like 'fixed top-0 left-0 flex h-full w-full'

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              className="relative flex h-4/5 w-5/6 flex-col items-center justify-between rounded-2xl bg-white p-6 shadow-[0_4px_4px_rgba(0,0,0,0.25)] lg:h-fit lg:w-3/5 xl:w-[35%]"
Ahh I need to add a shadow to my modal too - thanks!

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              className="relative flex h-4/5 w-5/6 flex-col items-center justify-between rounded-2xl bg-white p-6 shadow-[0_4px_4px_rgba(0,0,0,0.25)] lg:h-fit lg:w-3/5 xl:w-[35%]"
You can remove the media screens - i.e lg:h-fit etc

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                <img alt="burger" className="h-[172.41px] w-[264px] grow rounded-[12px] border-0 p-2" src={PlaceHolderImage} />
Rather than px to set the height, use vh - viewport height, more responsive.

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                <img alt="burger" className="h-[172.41px] w-[264px] grow rounded-[12px] border-0 p-2" src={PlaceHolderImage} />
Same for anywhere with large sizes

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                <img alt="burger" className="h-[172.41px] w-[264px] grow rounded-[12px] border-0 p-2" src={PlaceHolderImage} />
Obviously use the original image too

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  <h5 className="font-poppins text-xl font-[600] text-[#333F4C]">{product.name}</h5>
dont need font-poppins here

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  <h5 className="font-poppins text-xl font-[600] text-[#333F4C]">{product.name}</h5>
use px for text - i.e text-[16px], easier to read for people coming onto the project

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  <h5 className="font-poppins text-xl font-[600] text-[#333F4C]">{product.name}</h5>
same for weights etc.

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                      <button className="flex h-10 w-10 items-center gap-3.5 rounded-md bg-[#E4EAEB] p-4" onClick={decrease}>
I dont think 'flex' is needed on the buttons?

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  className="gap-2.5py-4 flex grow justify-center border-2 border-solid border-[#A2AAB6] px-3"
gap-2.5py-2, needs a space somewhere in there

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  className="gap-2.5py-4 flex grow justify-center border-2 border-solid border-[#A2AAB6] px-3"
doesn't need flex I dont think

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    className="gap-2.5py-4 flex grow justify-center px-3"
same here

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    className="gap-2.5py-4 flex grow justify-center px-3"
same here

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    className="gap-2.5py-4 flex grow justify-center px-3"
don't need flex in buttons

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +      ) : null}
should have a message here, saying something like 'No allergens' - maybe a bit more elaborate than that

2023-01-30 15:58 UTC, harrystead2 commented on src/components/ProductCard/ProductCard.tsx
> +      <button onClick={() => setShowModal(true)}>
do we want to make the whole productcard clickable, or just the add button?

2023-01-30 15:58 UTC, harrystead2 commented on src/context/OrderContext.tsx
> +  const ordersFunctions = useMemo(() => ({ localOrder, addToLocalOrder, removeProduct, setOrderId, removeLocalOrder }), [localOrder]);
rename this to orderProvider

2023-01-30 15:58 UTC, harrystead2 commented on src/context/orderReducer.tsx
> +          ...localOrder.lineItems,
Maybe swap these two around, so that create is first and edit second

2023-01-30 15:58 UTC, harrystead2 commented on src/components/Icons/CheckBoxIcon.tsx
> +
do we need an empty checkbox component too?

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  showModal: boolean;
rename showModal prop to 'showProductModal'

2023-01-30 15:58 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +       bg-black bg-opacity-25 outline-none focus:outline-none"
don't need the outline, nor the focus

2023-01-30 15:59 UTC, harrystead2 commented
- The modal div padding needs to be less

2023-01-30 16:00 UTC, harrystead2 commented
title should be inline with the image

2023-01-30 16:00 UTC, harrystead2 commented
more padding between buttons and allergens

2023-01-30 16:01 UTC, harrystead2 commented
quantity buttons should be inline with bottom of the image

2023-01-31 15:29 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                      <button className="flex h-10 w-10 items-center gap-3.5 rounded-md bg-[#E4EAEB] p-4" onClick={decrease}>
Is it not needed for the 'items-center'?

2023-02-01 13:22 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                <img alt="burger" className="h-[172.41px] w-[264px] grow rounded-[12px] border-0 p-2" src={PlaceHolderImage} />
Do you mean the one on figma or the on in use in the menu? They have different proportions

2023-02-01 13:23 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  <h5 className="font-poppins text-xl font-[600] text-[#333F4C]">{product.name}</h5>
Done

2023-02-01 13:25 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  <h5 className="font-poppins text-xl font-[600] text-[#333F4C]">{product.name}</h5>
done

2023-02-01 13:29 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  className="gap-2.5py-4 flex grow justify-center border-2 border-solid border-[#A2AAB6] px-3"
Done

2023-02-01 13:29 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    className="gap-2.5py-4 flex grow justify-center px-3"
Done

2023-02-01 13:30 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    className="gap-2.5py-4 flex grow justify-center px-3"
Done

2023-02-01 13:35 UTC, NogaAD commented on src/components/ProductCard/ProductCard.tsx
> +      <button onClick={() => setShowModal(true)}>
The postcard was clickable in the flow on figma

2023-02-01 13:37 UTC, NogaAD commented on src/context/OrderContext.tsx
> +  const ordersFunctions = useMemo(() => ({ localOrder, addToLocalOrder, removeProduct, setOrderId, removeLocalOrder }), [localOrder]);
Done

2023-02-01 13:41 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  showModal: boolean;
Done

2023-02-02 09:21 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    <button className="flex h-10 w-10 items-center gap-3.5 rounded-md bg-[#E4EAEB] p-4" onClick={decrease}>
shouldn't need flex on the buttons. to center the text within the button - it should just need 'text-center' on either the buttons or the div

2023-02-02 09:21 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +      ) : null}
this still needs adding

2023-02-02 09:22 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <img alt="burger" className="h-[25vh] w-[30vw] rounded-[16px]" src={PlaceHolderImage} />
Add 'object-cover' to image

2023-02-02 09:24 UTC, harrystead2 commented
Looks good!

2023-02-02 09:30 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +      ) : null}
This null is for the showProductModal, But I'll add a check for the allergens

2023-02-02 09:42 UTC, harrystead2 commented on src/components/MenuProductModal/MenuProductModal.tsx
> +      ) : null}
Oh yes, in that case just have - showmodal && ()

2023-02-02 10:02 UTC, mbaltrimas requested changes

2023-02-02 10:02 UTC, mbaltrimas commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                  Add to order £{(product.price * counter * 1e2) / 1e2}
I've noticed that this method of rounding seems to be quite common within this project, maybe we could have it in a reusable utility function to avoid duplicate code?

2023-02-02 10:02 UTC, mbaltrimas commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  };
this could be combined into a single function that takes in a positive/negative number to increase/decrease the counter

2023-02-02 10:50 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +  };
Done

2023-02-02 10:51 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +              <img alt="burger" className="h-[25vh] w-[30vw] rounded-[16px]" src={PlaceHolderImage} />
Done

2023-02-02 10:51 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +                    <button className="flex h-10 w-10 items-center gap-3.5 rounded-md bg-[#E4EAEB] p-4" onClick={decrease}>
Done

2023-02-02 10:51 UTC, NogaAD commented on src/components/MenuProductModal/MenuProductModal.tsx
> +      ) : null}
Done

2023-02-02 11:54 UTC, mbaltrimas approved these changes
lgtm!

2023-02-02 11:55 UTC, harrystead2 approved these changes

2023-02-02 11:58 UTC, merged